version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  keycloak:
#    build: ../../../..
    container_name: keycloak-auth-service
    image: quay.io/keycloak/keycloak:26.2.3
#    user: root
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres/pdb
#
#      KC_DB_USERNAME: admin
#      KC_DB_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-silent-king-a554g8b1.us-east-2.aws.neon.tech/keycloak?sslmode=require
      KC_DB_USERNAME: keycloak_owner
      KC_DB_PASSWORD: nJq5gC4hbkWU
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
#      KC_PROXY: edge
#      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
#      KC_FEATURES: token-exchange,admin-fine-grained-authz
#      KC_SPI_THEME_DEFAULT: 'my-theme'
#      KC_HOSTNAME: localhost
#      KC_PROXY_HEADERS: xforwarded,forwarded
#      PROXY_ADDRESS_FORWARDING: true
    ports:
      - "8083:8080"
    command:
      - start-dev
    volumes:
      - ./realm.json:/tmp/realm.json
      - ./extensions:/opt/keycloak/providers/
#      - ./themes/my-theme:/opt/keycloak/themes/my-theme
networks:
  local_network:
    driver: local



